version: "3.5"
services:
  ${repository}:
    image: redis:5.0.7
    hostname: ${repository}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    # volumes:
    #   - "/var/docker/${repository}/data:/data"
    networks:
      - online
networks:
  online:
    external: true
    name: online
