version: "3.5"
services:
  ${repository}:
    image: redis:5.0.6
    hostname: ${repository}
    user: root
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    volumes:
      - "/var/docker/${repository}/data:/data"
    networks:
      - ${repository}net
networks:
  ${repository}net:
    name: ${repository}net
